---
title: "2_Grouping_by_hemisphere_and_getting_occurrence_n"
author: "Mireia Valle"
date: "19/7/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warming = FALSE)
```

### Loading required libraries

```{r}
library(tidyverse)
library(R.utils) #loadToEnv
```

### Reading species table where hemisphere info has been gathered

```{r}
species <- read.csv (here::here ("data", "derived_data", "outputs_for_modelling", "species_for_modelling.csv"),  sep = ",")
head(species)

species <- species %>% 
  select(-X)

head(species)

unique(species$hemispheres)

n <- data.frame(species$SP)

names(n)

n <- n %>% 
  dplyr::rename (id = "species.SP")

n <- str_remove(n$id, "SP")

n <- as.numeric (n)

```

## Loading species data

```{r}
for(i in n ){
  a <- loadToEnv(file.path("data", "derived_data", "outputs_for_modelling","pa_environment",paste0("SP",i,".RData")))[[paste0("SP",i)]]
  a <- a %>% 
    mutate (SP_id = paste0("SP", i)) %>% 
    dplyr::filter (status == 1)
  
  #a<- select(a, sst, depth, SP_id)
  nam<-paste0("SP",i,sep="")
  assign(nam,a)
  }
```


```{r}
for (i in n){
plot(-depth~lat,data=get(paste0("SP",i)),
     main=paste0("SP",i))
}
```

## Creating species list by hemisphere

```{r}
unique (species$hemispheres)
```


### **Northern hemisphere** 

```{r}

# get the list of species that are distributed in the northern hemisphere, their RData must be saved the "north" folder
species_north <- species %>% 
  filter (hemispheres %in% c("north", "north & south"))

write.csv(species_north, file=here::here ("data", "derived_data", "0_depth_vs_lat", "species_list_north_bs.csv"))

# transform to a list
species_north_SP <- list (species_north$SP)

species_north_SP

# save
save (species_north_SP, file = here::here ("data", "derived_data", "0_depth_vs_lat", "species_north_SP_bs.RData"))
```

### **Sourthen hemisphere**

```{r}
# get the list of species that are distributed in the southern hemisphere, their RData must be saved the "south" folder
species_south <- species %>% 
  filter (hemispheres %in% c("south", "north & south"))

##guardamos la tabla en la que vamos a basar todo el resto de análisis

write.csv(species_south, file=here::here ("data", "derived_data", "0_depth_vs_lat", "species_list_south_bs.csv"))

# transform to a list
species_south_SP <- list (species_south$SP)

species_south_SP

# save
save (species_south_SP, file = here::here ("data", "derived_data", "0_depth_vs_lat", "species_south_SP_bs.RData"))

```

