---
title: "01_scam"
author: "Mireia Valle based on previous code from Guillem Chust, Leire Ibaibarriaga, Leire Citores, Eduardo Ramirez-Romero"
date: "2023-09-20"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warming = FALSE)
```

### Script information

With this script we generate a sc-gam models for each species and we save them

### Loading required libraries

```{r}
library(scam)
#library(mgcv)
library(plotmo)
library(rgdal)
library(ggplot2)
library(dplyr)
library(fields) #imageplot
library(maps) #map world
library(raster)
library(RColorBrewer)#color palette

#SDMTools - install RTools and follow: https://cran.r-project.org/bin/windows/Rtools/
#install.packages("remotes")
#remotes::install_version("SDMTools", "1.1-221.2")
library(SDMTools)
library(dismo)
library(stringr)
library(readxl)

library(R.utils) #loadToEnv
```

## Loading species data occurrences and pseudoabsences 50% of prevalence
```{r}
species <- read.csv (here::here ("data", "derived_data","outputs_for_modelling", "species_for_modelling.csv"),  sep = ",")

species <- species %>% 
  dplyr:: select ( -X) 

names <- read_excel (here::here ("data", "derived_data", "01_species_catches", "fish_and_tuna_long_list_75_Atlantic.xlsx"))

filenames_sp <- names$TaxonName

head(names)

n <- data.frame(species$SP)

names(n)

n <- n %>% 
  dplyr::rename (id = "species.SP")

n <- str_remove(n$id, "SP")

n <- as.numeric (n)

n <- c(12, 18, 28, 34, 76, 11,  1,  2,  3,  5,  6,  8,  9, 10, 19, 21, 22, 23, 31, 35, 36, 37, 38, 42, 50, 53, 61, 71)

```

Loop to build scams by species with sp = 0.00001 and default k = 8 and plevel  = 0.05
```{r}
for(i in n ){
  
  #Load species presence and pseudoabsence data from Training Regions 
  dat <- loadToEnv(file.path("data", "derived_data" , "outputs_for_modelling", "TR_pa_environment", paste0("SP",i, ".RData")))[[paste0("SP",i)]]

  
  #Load scgam model ORIGINAL MODEL

  res <- loadToEnv(file.path("data", "derived_data" , "models_sp00001",paste0("model_SP",i,".RData")))[[paste0("model_SP",i)]]
  
  scgam <- res$smod[[length(res$smod)]]
  
  v_summary <- summary(scgam)
  
  # isolate the formula
  formula <- v_summary[["formula"]]  
      
  # Model fit
  sp <- unique(scgam$sp)
  res <- scam (formula, family=binomial(link="logit"), 
                        data=dat, sp=rep(sp,length(res$svars)))

  # give again the proper name
  assign(paste0("model_SP",i), res)
  
  # save files after removing outliers
  save (list=paste0("model_SP",i), file = here::here ("data", "derived_data" , "models_sp00001", "validation_over_TR", "original_models_using_TRdatasets", paste0("model_SP",i, ".RData")))
  
}
```


Loop to build scams by species with sp = 0.001 and default k = 8 and plevel  = 0.05
```{r}
n <- c(30, 66)

for(i in n ){
  
  #Load species presence and pseudoabsence data from Training Regions 
  dat <- loadToEnv(file.path("data", "derived_data" , "outputs_for_modelling", "TR_pa_environment", paste0("SP",i, ".RData")))[[paste0("SP",i)]]

  
  #Load scgam model ORIGINAL MODEL

  res <- loadToEnv(file.path("data", "derived_data" , "models_sp00001",paste0("model_SP",i,".RData")))[[paste0("model_SP",i)]]
  
  scgam <- res$smod[[length(res$smod)]]
  
  v_summary <- summary(scgam)
  
  # isolate the formula
  formula <- v_summary[["formula"]]  
      
  # Model fit
  sp <- 0.001
  res <- scam (formula, family=binomial(link="logit"), 
                        data=dat, sp=rep(sp,length(res$svars)))

  # give again the proper name
  assign(paste0("model_SP",i), res)
  
  # save files after removing outliers
  save (list=paste0("model_SP",i), file = here::here ("data", "derived_data" , "models_sp00001", "validation_over_TR", "original_models_using_TRdatasets", paste0("model_SP",i, ".RData")))
  
}
```
