---
title: "plotmo_scams"
author: "Mireia Valle based on previous code from Guillem Chust, Leire Ibaibarriaga, Leire Citores, Eduardo Ramirez-Romero"
date: "2023-09-20"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warming = FALSE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file()) # to set up the root directory to the R project path. otherwise knitr uses the path of the markdown document as root directory
```

### Loading required libraries

```{r}
library(scam)
#library(mgcv)
library(plotmo)
library(rgdal)
library(ggplot2)
library(dplyr)
library(fields) #imageplot
library(maps) #map world
library(raster)
library(RColorBrewer)#color palette
library(tidyverse)
library(readxl)

#SDMTools - install RTools and follow: https://cran.r-project.org/bin/windows/Rtools/
#install.packages("remotes")
#remotes::install_version("SDMTools", "1.1-221.2")
library(SDMTools)
library(dismo)
library(R.utils) #loadToEnv
```

#Loading species id
```{r}
species <- read.csv (here::here ("data", "derived_data","outputs_for_modelling", "species_for_modelling.csv"),  sep = ",")

species <- species %>% 
  dplyr:: select (-X) 

names <- read_excel (here::here ("data", "derived_data", "01_species_catches", "fish_and_tuna_long_list_75_Atlantic.xlsx"))

filenames_sp <- names$TaxonName

n <- data.frame(species$SP)

names(n)

n <- n %>%
  dplyr::rename (id = "species.SP")

n <- str_remove(n$id, "SP")

n <- as.numeric (n)

```

Potential explanatory variables (as included for model selection):

```{r}
vars <- c("s(temp.v)",
          "s(sal.v)",
          "s(nit.v)",
          "s(dist_seabed.v)",
          "s(mld_relative_position.v)",
          "s(npp.v)")
```


Create an empty df to save the results from the scams
```{r}
scams_30spp <- as.data.frame(matrix(NA, ncol = 5 + 2 * length(vars),nrow = 76))
```

Loop to create and save plotmo figures and summaries for each species and chi.sq tables
```{r}
for (i in n){
   print(i)
  res <- loadToEnv(file.path("data", "derived_data" , "models_sp00001", "validation_over_TR", "original_models_using_TRdatasets", paste0("model_SP",i, ".RData")))[[paste0("model_SP",i)]]

  ###Extraigo resumen de analisis para todas las especies
   v_summary<-summary(res)
   s1<-v_summary$r.sq
   s2<-v_summary$dev.expl
   n_occ <- v_summary[["n"]]/2
   vars.l <- as.list (v_summary[["chi.sq"]])
   vars.names <- names(vars.l)
   var.incl <- as.numeric(vars %in% vars.names) # is the variable included in the final model?
   chisq <- rep(0, length(vars))
   chisq <- as.numeric(v_summary[["chi.sq"]])[match(vars, vars.names)] # match the order from the model with the variables tried

  # abro pdf para guardar plots por especie 
  png (here::here ("data", "derived_data" , "models_sp00001", "validation_over_TR", "original_models_using_TRdatasets", "plotmos", paste0("plotmo_SP",i, filenames_sp[i],".png")))
    plotmo(res,level = 0.95, pt.col=8)
  dev.off()

  # print the summary in the results folder
  scgam <- res
  {
    sink(here::here("data", "derived_data" , "models_sp00001", "validation_over_TR", "original_models_using_TRdatasets", "summaries", paste0("summary_SP",i, ".txt")))
      print(summary(scgam))
    sink()
  }

  scams_30spp[i, ] <- data.frame(paste0("SP",i),
                               filenames_sp[i],
                               s1,
                               s2, 
                               n_occ, 
                               t(var.incl), 
                               t(chisq))
} # end of loop

names(scams_30spp) <- c("SP", "SN", "r.sq", "dev.expl", "n_occ", vars, paste0("chisq_",vars))

scams_30spp <- scams_30spp %>% 
  drop_na(SP)

write.csv(scams_30spp, file=here::here ("data", "derived_data" , "models_sp00001", "validation_over_TR", "original_models_using_TRdatasets", "summary_scams_30spp.csv"))
```



