---
title: "Plot_sum_prob_for_3D"
author: "M Valle"
date: "7/7/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warming = FALSE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file()) # to set up the root directory to the R project path. otherwise knitr uses the path of the markdown document as root directory
```

Loading libraries
```{r}
library(sf)
library(rgdal)
library(stringr)
library(tidyverse)
library(ggpubr)
library(hrbrthemes) # theme_ipsum
library(png)
library(raster)
library(maptools) #mapping
library(maps)        # some basic country maps
library(mapdata)     # higher resolution maps
library(marmap)      # access global topography data
#devtools::install_github("eliocamp/metR@dev")
library(metR)
library(readxl)
```

# Basic map ---------------------------------------------------------------
```{r}

# basic map data

global <- map_data("worldHires")

```

#Loading selected species for modelling 
```{r}
species <- read.csv (here::here ("data", "derived_data","outputs_for_modelling", "species_for_modelling.csv"),  sep = ",")

species <- species %>% 
  dplyr:: select ( -X) 

names <- read_excel (here::here ("data", "derived_data", "01_species_catches", "fish_and_tuna_long_list_75_Atlantic.xlsx"))

filenames_sp <- names$TaxonName


head(names)

n <- data.frame(species$SP)

names(n)

n <- n %>% 
  dplyr::rename (id = "species.SP")

n <- str_remove(n$id, "SP")

n <- as.numeric (n)
```


```{r}
for(i in n){
  
  print(i)
    
    #Load SP data
   load(here::here ("data", "derived_data", "outputs_for_modelling", "pa_environment", paste0("SP",i,".Rdata")))
  
  a<-get(paste0("SP",i), env = new.env())
  
  # filter to keep only occurrences and rename lon lat columns
  a <- a %>% 
    dplyr::filter (status == 1) %>% 
    dplyr::select (lon, lat, depth, status) %>% 
    dplyr::rename (x = "lon", 
            y = "lat")
  
  #load sum probability map and rename the sum probability column
  sum_prob <- raster(here::here ("data", "derived_data", "models_sp00001", "rasters_set_by_species", "sum_cumulative_probabilty_HSM", paste0("cumulative_prob_sum_SP",i, ".tif")))

  
  #Transform to dataframe and rename the sum probability column
  sum_prob.df <- as.data.frame(sum_prob, xy= TRUE) %>% 
    dplyr::rename (sum_prob = paste0("cumulative_prob_sum_SP", i))
  
  #calculate total summed probability
  summary(sum_prob.df$sum_prob)
  
  #scale probability value to 0-1 range
    sum_prob.df_scaled <- sum_prob.df %>% 
    dplyr::mutate (sum_prob_scaled = (sum_prob-min(sum_prob.df$sum_prob))/(max(sum_prob.df$sum_prob)-min(sum_prob.df$sum_prob)))
    
    summary(sum_prob.df_scaled)
    
    #keep only scaled probability and xy
    sum_prob.df_scaled <- sum_prob.df_scaled %>%
      dplyr::select(x, y, sum_prob_scaled)
    
    summary(sum_prob.df_scaled)
    
    #transform to raster
    sum_prob.df_scaled.r <- rasterFromXYZ(sum_prob.df_scaled)
    
    crs(sum_prob.df_scaled.r) <- crs(sum_prob)
    
  #save scaled raster
    writeRaster(sum_prob.df_scaled.r,
            filename=here::here ("data", "derived_data", "models_sp00001", "rasters_set_by_species", "sum_cumulative_probabilty_HSM_scaled_0_1", paste0("sum_cumulative_probabilty_HSM_scaled_0_1_SP",i,"_", filenames_sp[i])),
            format="GTiff",
            overwrite=TRUE,
            options=c("INTERLEAVE=BAND","COMPRESS=LZW"))
    
  
# GENERATE REVIEW PLOTS

# grey color scale: https://www.mango-solutions.com/50-shades-of-grey-according-to-r/
 # https://dev.to/finnhvman/grayscale-color-palette-with-equal-contrast-ratios-2pgl

p <- ggplot() +
   #plot occurrence points
  #geom_raster(data = sum_prob.df, aes(x = x, y = y, fill=sum_prob))+
  geom_point(data = sum_prob.df_scaled, aes(x = x, y = y, colour = sum_prob_scaled), size = 1)+
    scale_colour_distiller(name = paste("Cumulative prob."), palette = "YlOrRd", direction = +1, limits = c(min(sum_prob.df_scaled$sum_prob_scaled), max(sum_prob.df_scaled$sum_prob_scaled)), na.value="transparent")+
    #plot occurrence points
    geom_point(data = a, aes(x = x, y = y,  fill= "GBIF/OBIS occurrences"), color= "blue", size = 0.5)+
    labs(fill = "")  +
  theme_pubclean(base_size = 50)+
  annotation_map(map=global, fill="#999999")+
  scale_y_latitude(limits = c(-80, 80))+
  scale_x_longitude(limits = c(-100,60, ticks = 50))+
    theme(panel.background = element_blank(),
          #text = element_text(size = 22),
          #axis.text.x = element_blank(),
          #axis.ticks.x = element_blank(),
          legend.position="right")+
    # title
    labs(title= paste0(filenames_sp[i], "_SP", i),
         y="Latitude"
         ,x = "Longitude")+
  guides(fill = guide_legend(order = 1, override.aes = list(size=10)),
         colour = guide_legend(order = 2, override.aes = list(size=10)))


ggsave(filename= paste0("sum_prob_scaled_SP",i,".tif"), plot=p, device="tiff",
         path=here::here ("product", "figures", "3D", "sum_prob_scaled_HSM"),
         height=22, width=30,
         units="in", dpi=300)


}

```

