---
title: "create sum_prob profiles along depth gradient"
author: "Mireia Valle modifing code from Eduardo Ramírez-Romero"
date: "17/2/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warming = FALSE)
```

### Script information

With this script we create lat profiles of sum_prob along a transect

Project: IM-20-MISSION

### Loading required libraries
```{r}
library (dplyr)
library(raster) # package for raster manipulation
library(MALDIquant)
library(rgdal)
library(plotly)
library(here)
library(tidyverse)
library(reshape2)
library(sf)
library(prevR)
library(gtools) #mixedsort
library(readxl)
```

### Load species SPid and names
```{r}
species <- read.csv (here::here ("data", "derived_data","outputs_for_modelling", "species_for_modelling.csv"),  sep = ",")

species <- species %>% 
  dplyr:: select ( -X) 

names <- read_excel (here::here ("data", "derived_data", "01_species_catches", "fish_and_tuna_long_list_75_Atlantic.xlsx"))

filenames_sp <- names$TaxonName


head(names)

n <- data.frame(species$SP)

names(n)

n <- n %>% 
  dplyr::rename (id = "species.SP")

n <- str_remove(n$id, "SP")

n <- as.numeric (n)
```

# Loop to generate sum prob value along latitude

```{r}
for (i in n) {

#-------------------------------------------------------------#  
#1) Load stack with cumulative probability value maps by depth level 
#--------------------------------------------------------------------#
  
sum_prob_brick <- brick (here::here ("data", "derived_data", "models_sp00001", "rasters_set_by_species","cumulative_prob_bricks", paste0("HSM_2_cumulative_prob_brick_SP",i,".tif")))

dim(sum_prob_brick)

#plot(sum_prob_brick[[1]])
  
#--------------------------------------------------------------#
#2) Prepare the data to plot the profile along the latitude gradient
#----------------------------------------------------------------------#

# divide in latitudinal zones
zones <- init(sum_prob_brick, v='y')

#plot(zones)

# summarize probability along latitudinal zones calculating the sum

zsum <- data.frame(zonal(sum_prob_brick, zones, 'sum', na.rm=TRUE))

summary(zsum)

# give again the proper name

assign(paste0("zsum_SP",i), zsum)


save (list=paste0("zsum_SP",i), file = here::here ("data", "derived_data", "models_sp00001", "lat_profiles", "sum_cumulative_prob", paste0("z_prob_sum_SP",i, ".RData")))

print (i)  
}# end of loop

```

