---
title: "01_presence_pseudoabsence_fusion"
author: "Mireia Valle, Leire Ibaibarriaga and Eduardo Ramirez-Romero"
date: "5/11/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

#Script info

Script to join presence and pseudoabsence data

#Load libraries
```{r}
library(stringr)
library("xlsx")
library (dplyr)
library(readxl)
library(ggplot2)
library(here) #enable easy file referencing 
library(dplyr) #data cleaning
library(ggplot2) #plotting
library(cowplot) #plotting more than one plot
library(rgeos) #mapping
library(sp) #mapping
library(rgdal) #mapping
library(maptools) #mapping
library(maps)        # some basic country maps
library(mapdata)     # higher resolution maps
library(marmap)      # access global topography data
library(plyr) #mapping
library(dplyr)
library(tidyverse)
library(readxl)
library(RColorBrewer)# plots
library(ggpointdensity)
library(gridExtra)

```


# Basic map for plotting
```{r}
# basic map data

global <- map_data("worldHires")

# get bathymetry data

# basic ggplot

p0 <- ggplot() +
  # geom_contour(data=bathy.df, aes(x,y,z=z), breaks=c(-100, -200), col="grey")+
  annotation_map(map=global, fill="grey")+
  coord_sf(xlim=c(-90,50), ylim=c(-90,90))+
  xlab("")+
  ylab("")

```

# Load data
```{r}
#pseudoabsence set

load(here::here ("data", "derived_data", "03_create_pseudoabsences","pseudoabsences_environmental.RData"))

pseudo_complete <- data
rm(data)

names (pseudo_complete)


#Load species list

species <- read.csv (here::here ("data", "derived_data","outputs_for_modelling", "species_for_modelling.csv"),  sep = ",")

 species <- species %>%
   dplyr:: select (-X)


names <- read_excel (here::here ("data", "derived_data", "01_species_catches", "fish_and_tuna_long_list_75_Atlantic.xlsx"))

filenames_sp <- names$TaxonName

head(names)

n <- data.frame(species$SP)

names(n)

n <- n %>%
   dplyr::rename (id = "species.SP")

 n <- str_remove(n$id, "SP")

 n <- as.numeric (n)
```

Loop for joining the presence and pseudoabsence data and ploting
```{r}
for(i in n ){
 
    load(here::here("data", "derived_data", "04_extracted_environment", "occurrences_environment", paste0("SP",i,".Rdata")))
    
    data<-get(paste0("SP",i), env = new.env())
 
    occ<-data %>%
      dplyr::select(lon,
                    lat,
                    depth,
                    sst,
                    temp.v,
                    sss,
                    sal.v,
                    nit.s,
                    nit.v,
                    dist_seabed.s,
                    dist_seabed.v,
                    mld_rel.s,
                    mld_relative_position.v,
                    npp.s,
                    npp.v,
                    status)
 
    occ <- drop_na(occ)
 
    #numero de presencias
    n_occ<- nrow(occ)
 
    #new pseudoabsence matrix avoiding to consider pseudoabsences where presence has been recorder
 
    pseudo<- pseudo_complete %>%
      dplyr::select(lon,
                    lat,
                    depth,
                    sst,
                    temp.v,
                    sss,
                    sal.v,
                    nit.s,
                    nit.v,
                    dist_seabed.s,
                    dist_seabed.v,
                    mld_rel.s,
                    mld_relative_position.v,
                    npp.s,
                    npp.v,
                    status) %>%
      anti_join(occ,by=c("lon","lat","depth"))
 
     pseudo <- drop_na(pseudo)

   #Muestra aleatoria para vertical
    set.seed(i)
    pseudo<-pseudo %>% distinct(lon,lat, .keep_all = T)
    sv <- sample(nrow(data.frame(pseudo$lon)),size=n_occ,replace=TRUE)
    pseudo <- pseudo[sv,]
 
    p0 +
      geom_point(data = pseudo, aes(x = lon, y = lat, colour = factor(status)), size = 1) +
      ggtitle(paste0("distribution data ", "SP",i, " n=",(nrow(pseudo))))
 
    #Fusiono, concateno
    pa<-rbind(occ,pseudo)
 
     #abro pdf para guardar plots por especie
    png (here::here ("product", "figures", "distribution_maps", paste("pa_map_",data$SP_id,filenames_sp[i],".png")))
 
    #map of occurrences
    p1 <- p0 +
      geom_point(data = pa, aes(x = lon, y = lat, colour = factor(status)), size = 1) +
      ggtitle(paste0("distribution data ", data$SP_id,": ", data$SN ," n_occ=",(nrow(pa)/2)))
    print(p1)
    dev.off()
 
    #give again the proper name
 
  assign(data$SP_id[i], pa)
 
    #save files after removing outliers
 
  save (list=data$SP_id[i], file = here::here ("data", "derived_data", "outputs_for_modelling", "pa_environment", paste0(data$SP_id[i], ".RData")))
 
  print(data$SP_id[i])
 
  }

```

