---
title: "03_removing_outliers_automatic"
author: "Leire Ibaibarriaga & Mireia Valle"
date: "2022-02-03"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warming = FALSE)
```

# Description

Script to remove outliers from the species occurrence data based on distance.

# Load libraries ---------------------------------------------------
```{r}
library(here) #enable easy file referencing 
library(dplyr) #data cleaning
library(ggplot2) #plotting
library(cowplot) #plotting more than one plot
library(rgeos) #mapping
library(sp) #mapping
library(rgdal) #mapping
library(maptools) #mapping
library(maps)        # some basic country maps
library(mapdata)     # higher resolution maps
library(marmap)      # access global topography data
library(plyr) #mapping
library(dplyr)
library(tidyverse)
library(readxl)
library(RColorBrewer)# plots
library(ggpointdensity)
library(gridExtra)
library(CoordinateCleaner)

# general settings for ggplot2

theme_set(theme_bw(base_size=14) + theme(plot.title = element_text(hjust = 0.5)))
```

# Data Preparation --------------------------------------------------------
```{r}
# load species data

species <- read.csv (here::here ("data","derived_data", "02_species_occurrences", "species_list_pa_top_63.csv"),  sep = ",")

species <- species %>% 
  dplyr::select (-X) %>% 
  add_column(hemispheres = NA) %>% 
  add_column(outliers = NA) %>% 
  add_column(n_occ = NA)

head (species)
nrow(species)
```

# Basic map --------------------------------------------------------
```{r}
# basic map data

global <- map_data("worldHires")

# get bathymetry data

# bathy <- getNOAA.bathy(lon1=-83,lon2=20,lat1=-90,lat2=90, resolution = 4, keep=FALSE, antimeridian=FALSE)
# bathy.df <- fortify(bathy)

# basic ggplot

p0 <- ggplot() +
  # geom_contour(data=bathy.df, aes(x,y,z=z), breaks=c(-100, -200), col="grey")+
  annotation_map(map=global, fill="grey")+
  coord_sf(xlim=c(-90,50), ylim=c(-90,90))+
  xlab("")+
  ylab("")
print(p0)

# Remove outliers by species ----------------------------------------------

# The method that gives results closest to the manual identification is the distance method from CoordinateCleaner
# Therefore, we remove the outliers identified by the distance method and we save the cleaned data sets

for (i in 1:nrow(species)){
  # species, i is the row number and species$SP[i] is the species data name (which is not always paste0("SP",i) )
  
  species[i,]
  
  # Loading data SPi (e.g. SP1, SP2, ... SP76)
  
  load(here::here("data", "derived_data", "02_species_occurrences", "01_species_occurrences_clean_63", paste0(species$SP[i],".RData")))
  
  # Give a generic name
  
  SP <- get(species$SP[i])
  
  # summary, structure, head, dimension of the file
  summary(SP)
  str(SP)
  head(SP)
  dim(SP)

 # add SP_id column
  SP <- SP %>% 
    mutate (SP_id = species$SP[i]) 

  # find outliers based on distance method
  out.dist <- cc_outl(x=SP,
                lon = "decimalLongitude", lat = "decimalLatitude",
                species = "SP_id",
                method="distance", tdi=1000, # distance method with tdi=1000km
                thinning=T, thinning_res=0.5,
                value="flagged") 

  # remove outliers from the data
  
  SP <- SP[out.dist, ]
  
  # give again the proper name
  
  assign(species$SP[i], SP)
  
  # complete the information in the species object

  species$hemispheres[i] <- ifelse(all(SP$decimalLatitude>0), "north", ifelse(all(SP$decimalLatitude<0), "south", "north & south"))
  species$outliers[i] <- sum(!out.dist) # number of outliers removed
  species$n_occ[i] <- nrow(SP) # number of occurrences after removing outliers

  # save files after removing outliers

  write.csv(species, file=here::here ("data","derived_data", "02_species_occurrences", "species_list_FINAL_hemispheres_automatic.csv"))

  # save files after removing outliers
  save (list=species$SP[i], file = here::here ("data","derived_data", "02_species_occurrences", "02_species_occurrences_no_outliers_automatic", paste0(species$SP[i], "new.RData")))
  
} # end of loop for species
  
```


