---
title: "Create_points_over3Dgrid by training regions"
author: "Mireia Valle based on the code used to create the points over the 3D grid for the entire Atlantic"
date: "2023-09-20"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warming = FALSE)
```

Script to create points over the 3D grid of the training regions.

# Loading required libraries
```{r}
library(rgeos)
library(sp)
library(rgdal)
library(raster)
library(data.table)
library(dplyr)
library(ncdf4)

# library(MALDIquant)
library(gtools)
library(here)
library(ggplot2)
```

# Load data
```{r}

FAO<- readOGR(here::here("data", "raw_data", "FAO_Areas", "FAO_AREAS.shp"))

### Load 3D data

temp_3d_1000 <- brick(here::here("data", "derived_data", "outputs_for_modelling","variables","temp_3d_1000.tif"))

#plot(temp_3d_1000)

### transform brickraster to points
xyz <- data.frame(rasterToPoints(temp_3d_1000))

#setting formats
dat <- data.frame(cbind(xyz$x,xyz$y))
ptos<-as.data.table(dat,keep.columnnames=TRUE)


coordinates(ptos) <- ~ X1 + X2


proj4string(ptos) <-proj4string(FAO)
```

# load species list
```{r}
species <- read.csv (here::here ("data", "derived_data", "outputs_for_modelling", "species_for_modelling.csv"),  sep = ",")

species <- species %>% 
  dplyr:: select (-X)

n <- data.frame(species$SP)

names(n)

n <- n %>% 
  dplyr::rename (id = "species.SP")

n <- str_remove(n$id, "SP")

n <- as.numeric (n)

```

Loop to create points over the 3D space of each training region

```{r}

for(i in n ){
  
   load(here::here("data", "derived_data", "outputs_for_modelling", "training_regions", paste0("trainingRegions_SP",i,".Rdata")))
  
  tr<-get(paste0("trainingRegion_SP",i), env = new.env())
  
  tr.sf <- st_as_sf(tr)
  
## convert the geometry of the `sf` object to SpatialPolygons
spd <- sf::as_Spatial(st_geometry(tr), IDs = as.character(1:nrow(tr)))

class(spd)

## grab the data from the sf object
df <- tr
df$geometry <- NULL
df <- as.data.frame(tr)

## create the SpatialPolygonsDataFrame
spd <- sp::SpatialPolygonsDataFrame(spd, data = df)
  
plot(spd)  
  
### select only those points within FAO Atlantic
ptos.atl<-data.frame(subset(xyz , !is.na(over(ptos, spd)[,1])))

levels<-ptos.atl[,3:49]
levels[!is.na(levels)]<-1

ptos.atl<-cbind(ptos.atl$x,ptos.atl$y,levels)


l<-data.frame(as.vector(extent(temp_3d_1000)))
lon<-seq(l[1,1],l[2,1], 0.25)
lat<-seq(l[3,1],l[4,1], 0.25)


## create depth data frame
nc_data <- nc_open(here::here("data", "raw_data", "variables", "TEMP", "woa18_decav81B0_t00_04.nc"))
depth <- ncvar_get(nc_data, "depth")
depth<-depth[1:47]
depth<-data.frame(depth)

####save 
save(lon,lat,depth, ptos.atl,file= here::here ("data", "derived_data", "03_create_pseudoabsences", "by_species", paste0("PsA_atl_SP", i, ".RData")))
     
}

```

