---
title: "Create_pseudoabsences_by_training_regions"
author: "Mireia Valle based on the code used to create the points over the 3D grid for the entire Atlantic"
date: "2023-09-20"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warming = FALSE)
```

Script to create a set of pseudoabsences within the 3D grid for each species

# Loading required libraries
```{r}
library(rgeos)
library(sp)
library(rgdal)
library(raster)
library(data.table)
library(dplyr)
library(ncdf4)
# library(MALDIquant)
library(gtools)
library(here)
library(ggplot2)
```

#Load data
```{r}
# Load FAO (spatial multipolygon)
FAO<- readOGR(here::here("data", "raw_data", "FAO_AREAS", "FAO_AREAS.shp"))

#Load study area
FAO_Atl <- readOGR(here::here("data", "raw_data", "FAO_AREAS", "FAO_Atl.shp"))

plot(FAO_Atl)
```

# load species list
```{r}
species <- read.csv (here::here ("data", "derived_data", "outputs_for_modelling", "species_for_modelling.csv"),  sep = ",")

species <- species %>% 
  dplyr:: select (-X)

n <- data.frame(species$SP)

names(n)

n <- n %>% 
  dplyr::rename (id = "species.SP")

n <- str_remove(n$id, "SP")

n <- as.numeric (n)

```

Loop to load each species pseudoansences and extract the environmental data to the points  
```{r}

for(i in n ){

#load species occurrence data
#load(here::here("data","derived_data", "02_species_occurrences", "03_species_occurrences_aggregated", paste0("SP",i,".Rdata")))
  
    #Load species occurrences from Valle et al 2024 in order to get the same outputs 
  load(here::here("data","derived_data", "outputs_for_modelling", "pa_environment", paste0("SP",i,".Rdata")))

data<-get(paste0("SP",i), env = new.env())  

data <- data %>% 
  dplyr::filter (status == 1)
  
#calculate the number of occurrences of each species
size <- nrow(data)+2000

#in case you are not using the data from Valle et al 2024, then you keep the same size as the size of your aggregated occurrences. 

#size <- nrow(data) 
  
#Load 3D Grid points
load(here::here ("data", "derived_data", "03_create_pseudoabsences", "by_species", paste0("PsA_atl_SP", i, ".RData")))

colnames(ptos.atl)[1] <- "lon"
colnames(ptos.atl)[2] <- "lat"


lon_all<-rep(ptos.atl$lon,47)
lat_all<-rep(ptos.atl$lat,47)

levels<-ptos.atl[,3:49]

c<-data.frame()
d<-data.frame()

for (j in 1:47) {
  c<-data.frame(levels[,j]) %>% rbind(c)
  d<-data.frame(rep(depth[j,1],dim(levels)[1]))%>% rbind(d)
  
}


colnames(c)[1] <- "mask"
colnames(d)[1] <- "depth"


ptos<-cbind(lon_all,lat_all,d,c)
colnames(ptos)[1]<- "lon"
colnames(ptos)[2]<- "lat"

ptos.f<-ptos[!is.na(ptos$mask),]

### Random selection

set.seed(1)
s <- sample(nrow(ptos.f),size=size,replace=TRUE)
ps.sp <- ptos.f[s,]

summary(ps.sp)

save(ps.sp,file=here::here ("data","derived_data",  "03_create_pseudoabsences", "by_species", paste0("pseudo_absences_SP", i, ".RData")))

}

```

